spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/produto?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: postgres
    password: 123456
  jpa:
    show-sql: true
  flyway:
    enabled: true
